# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: 'http://www.alientronics.com.br/'
title: Alientronics
email: henrique.dias@alientronics.com.br
author: Henrique Dias
description: 'A Alientronics &eacute; um empresa de Porto Alegre - RS com foco em desenvolver solu&ccedil;&otilde;es para Internet das Coisas, visando monitorar e gerenciar melhor qualquer dispositivo que seja poss&iacute;vel conectar &agrave; internet.'
copyright: 'Copyright &copy; 2016 Alientronics. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    icon: envelope
    url: mailto:felipe@alientronics.com.br
